[tool.poetry]
name = "nonebot-plugin-autoreply"
version = "0.2.2"
description = "As the name suggests"
authors = ["lgc2333 <lgc2333@126.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
nonebot2 = ">=2.0.0rc1"
pydantic = "^1.10.4"
nonebot-adapter-onebot = ">=2.1.0"
typing-extensions = "^4.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
